### ISSUE TITLE
Serialization/Deserialization of treatmentplan object

### ISSUE THREAD

**Issue by SQuartinAS** [WinVector/vtreat#4]
I am interested in serializing a `treatmentplan` object to JSON, store it and later deserialize it and use it to prepare a new observation. I am using `jsonlite` for this but I am unable to `prepare` a new observation with the deserialized object. 

```
library("vtreat")
library("jsonlite")

load("test.RData")
class(treatmentDesign) <- "treatmentplan" #I had saved it as a list

treatmentDesignDeserialized <- unserializeJSON(serializeJSON(treatmentDesign, digits = 12))
```
Things start to get weird already, as the deserialized object almost doubled in size:

```
> object.size(treatmentDesign)
1791328 bytes
> object.size(treatmentDesignDeserialized)
3143408 bytes
```
But if I check for equality ...
```
> all.equal(treatmentDesign,
+           treatmentDesignDeserialized,
+           check.attributes = TRUE,
+           check.names = TRUE)
[1] TRUE
```

When I check for structure equality

```
> serializedeserialize <- capture.output(str(treatmentDesignDeserialized))
> originalfile <- capture.output(str(treatmentDesign))
> identical(originalfile, serializedeserialize)
[1] TRUE
```

Now, the `prepare` function works with the original loaded `treatmentplan`, but after serialization/deserialization it returns an error

```
> load("newObservationExample.RData")
> prepNewObs <- prepare(treatmentDesign, newObs, pruneSig = 0.1)
> 
> prepare(treatmentDesignDeserialized, newObs, pruneSig = 0.1)
 Error in vtreat$f(xcol, vtreat$args, doCollar) : 
  could not find function ".preProcCat" 
```

This looks a whole lot like [this](https://github.com/jeroenooms/jsonlite/issues/129), but the quick fix doesn't seem to work. I tried adding
`attr(treatmentDesignDeserialized$treatments, ".Environment") <- .GlobalEnv`

Any suggestions, have you done similar operations? There were no answers to the issue opened in `jsonlite`, hence reaching out for advice here.

There is an horrible workaround, which consists in  [exporting](http://stackoverflow.com/a/37833781/6060525) all hidden functions, but I'd really rather run away from this 'solution':
```
> # get all the function names
> r <- unclass(lsf.str(envir = asNamespace("vtreat"), all = TRUE))
> # create functions in the Global Env. with the same name
> for(name in r) eval(parse(text=paste0(name, '<-vtreat:::', name)))
> 
> prepNew <- prepare(treatmentDesignDeserialized, newObs, pruneSig = 0.1)
> 
> all.equal(prepNewObs, prepNew, tolerance = 10-8)
[1] TRUE
```

Thanks.

**Comment by JohnMount** [comment]
Right now you can not JSONlite to serialize vtreat treatment plans.  They can be stored, but not through that path.

<code>vtreat</code> uses functions and closure capture as a convenient way to save its treatment plan.  Some day if we can get a grant we would re-design the stored format to be "data only" for reasons of interoperability (being able to work across versions of vtreat, and being able to interoperate with future Spark and Python implementations).

vtreat can be saved/stored with R's native RDS methods:

<pre>
library(&quot;vtreat&quot;)
dTrainC &lt;- data.frame(x=c(&apos;a&apos;,&apos;a&apos;,&apos;a&apos;,&apos;b&apos;,&apos;b&apos;,NA,NA),
                      z=c(1,2,3,4,NA,6,NA),
                      y=c(FALSE,FALSE,TRUE,FALSE,TRUE,TRUE,TRUE))
treatmentsC &lt;- designTreatmentsC(dTrainC,colnames(dTrainC),&apos;y&apos;,TRUE)
saveRDS(treatmentsC,&apos;treatmentsC.RDS&apos;)
</pre>

Restart R.

<pre>
library(&quot;vtreat&quot;)
treatmentsC &lt;- readRDS(&apos;treatmentsC.RDS&apos;)
dTestC &lt;- data.frame(x=c(&apos;a&apos;,&apos;b&apos;,&apos;c&apos;,NA),z=c(10,20,30,NA))
dTestCTreated &lt;- prepare(treatmentsC,dTestC,pruneSig=c())
</pre>

Since vtreat treatment plans are not pure data it isn't expected something like JSONlite can successfully load/store it.

**Comment by SQuartinAS** [comment]
Thank you!
